# Generated by Django 4.0 on 2022-11-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likescomment',
            old_name='liked',
            new_name='is_liked',
        ),
    ]
