# Generated by Django 4.1.3 on 2022-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
