# Generated by Django 4.0 on 2022-11-17 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('25deb5ed-64b8-4063-b13a-01f01e56e6ba'), primary_key=True, serialize=False, unique=True),
        ),
    ]
