# Generated by Django 4.1.3 on 2022-11-17 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('6cbcc07c-dafc-4cf8-96ed-251cd48d5992'), primary_key=True, serialize=False, unique=True),
        ),
    ]
