# Generated by Django 4.0 on 2022-11-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_user_is_active_alter_user_user_id'),
        ('Test', '0003_user_otp_user_otp_created_at_alter_user_user_id'),
    ]

    operations = [
    ]
