# Generated by Django 4.0 on 2022-11-18 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_merge_20221118_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('c08abd11-caa0-4028-b6ce-4e0bcbaf18f4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
