# Generated by Django 4.0 on 2022-11-23 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_alter_user_otp_created_at_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('25e014e8-55e7-454e-8d3d-4c3b2c29a333'), primary_key=True, serialize=False, unique=True),
        ),
    ]
