# Generated by Django 4.0 on 2022-11-23 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_user_is_verified_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('368bfdec-a892-4b02-8227-29c030f0a2e3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
