# Generated by Django 4.0 on 2022-11-22 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_merge_20221122_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('03a5e1e8-5b3d-4dd5-98ea-ce318d6def11'), primary_key=True, serialize=False, unique=True),
        ),
    ]
