# Generated by Django 4.0 on 2022-11-23 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f92d82d7-36f0-4202-adf5-d91922e30700'), primary_key=True, serialize=False, unique=True),
        ),
    ]
