# Generated by Django 4.0 on 2022-11-22 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('e700f7b7-c1d1-4369-b56f-5125b0641f85'), primary_key=True, serialize=False, unique=True),
        ),
    ]
