# Generated by Django 4.0 on 2022-11-22 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0f0c3358-e896-4a9c-a5c7-8c0100a059e5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
