# Generated by Django 4.0 on 2022-11-22 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('77d7df3e-fccd-4e52-a54a-6bfe7f476790'), primary_key=True, serialize=False, unique=True),
        ),
    ]
