# Generated by Django 4.0 on 2022-11-22 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('433794fb-acfd-4fee-8632-1e420078faa9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
